### ISSUE TITLE
Need locations of storm drains

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/data-requests#2]
I could use the locations of storm drains in San Jose.
I want it to look like this:
https://github.com/qtrandev/adopt-a-drain/blob/master/db/seeds.csv

So what i'd need is lat and longs and some identifier the city uses for it.  I think that is it.

**Comment by mthong** [comment]
Can you check out the geospatial data provided in the link under "Storm Systems" on this page: http://www.sanjoseca.gov/index.aspx?NID=3308

Can you get what you need from the shapefile or KMZ file or do you need something else?

**Comment by 3vivekb** [comment]
This should work!  I can convert it to what I need.  I think I just need to brush up on my storm drain terminology.
