### ISSUE TITLE
City neighborhood - lat/long coordinates

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/data-requests#4]
Need lat/long coordinates for city neighborhoods to be able to filter fire incidents and other mapped items

**Comment by 3vivekb** [comment]
San Jose City Council Districts.
http://www.sanjoseca.gov/index.aspx?NID=3308

Also there seem to be neighborhoods here:
http://gisdata-csjdotgis.opendata.arcgis.com/datasets/578f3459ffae471d8d579f7058dfbd74_0
